import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Loader from "./Loader";
import NextTopLoader from "nextjs-toploader";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import Providerx from "./redux/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Md Asikur Rahman",
  description: "Generated by Md Asikur Rahman",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#2299DD" showAtBottom={false} />
          <SessionProvider session={session}>{children}</SessionProvider>
        {/* <NextTopLoader color="yellow" showAtBottom={true} /> */}
      </body>
    </html>
  );
}
